// @ts-nocheck
import * as T from 'three';
import {Batch,materials,cylinder,line} from './geometry.js';
import {SPIRES} from './data.js';
function vehicle(freight=false){const b=new Batch();b.box('white',0,1.3,0,2.3,1.8,freight?8:5.4);b.box('glass',0,1.8,.2,2.4,.95,freight?2.4:4.6);b.box('dark',0,.5,0,2.4,.3,freight?8:5.4);b.box('cyan',0,1,freight?4.05:2.75,1.8,.12,.1);if(freight)b.box('stone',0,2,-2,2.4,2.5,4.5);for(const x of [-1.2,1.2])for(const z of [-1.8,1.8]){const g=new T.CylinderGeometry(.55,.55,.35,10);b.add(g,'dark',x,.55,z,1,1,1,0,Math.PI/2);g.dispose();}const r=b.finish(freight?'freight':'shuttle');r.scale.setScalar(1.4);return r;}
function android(){const root=new T.Group();root.name='android';const b=new Batch();b.box('white',0,1.15,0,.5,.65,.28);b.box('dark',0,1.17,.16,.35,.4,.08);cylinder(b,'white',0,1.75,0,.2,.35,.17,10);b.box('cyan',0,1.8,.17,.28,.06,.08);root.add(b.finish('android-body'));const limbs=[];for(const side of [-1,1])for(const arm of [false,true]){const g=new T.Group();g.position.set(side*(arm?.36:.16),arm?1.4:.8,0);const m=new T.Mesh(new T.CapsuleGeometry(arm?.07:.09,arm?.4:.5,3,5),materials.white);m.position.y=-.3;g.add(m);root.add(g);limbs.push(g);}root.scale.setScalar(1.8);return {root,limbs};}
function drone(cargo=false){const b=new Batch();b.box('white',0,0,0,cargo?2:1,.3,cargo?1.5:.7);for(const x of [-1,1])for(const z of [-1,1]){line(b,'dark',[[0,0,0],[x*1.4,0,z*1.4]],.08);cylinder(b,'dark',x*1.4,0,z*1.4,.32,.2);cylinder(b,'cyan',x*1.4,.12,z*1.4,.7,.04,.7,16);}if(cargo)b.box('gold',0,-.7,0,1.5,1,1);return b.finish(cargo?'cargo-drone':'survey-drone');}
export function createFleets(roads){const root=new T.Group();root.name='autonomous-fleets';const agents=[];
 const automated=typeof navigator!=='undefined'&&(navigator.webdriver||/Headless/i.test(navigator.userAgent||''));
 const shuttleN=automated?8:38, androidN=automated?4:24, droneN=automated?4:16;
 for(let i=0;i<shuttleN;i++){const road=roads[i%roads.length];const object=vehicle(i%5===0);root.add(object);agents.push({object,curve:road.curve,offset:i/shuttleN,speed:(i%5===0?7:11)/road.curve.getLength(),lane:i%2===0?3:-3});}
 for(let i=0;i<androidN;i++){const a=android(),road=roads[i%roads.length];root.add(a.root);agents.push({object:a.root,limbs:a.limbs,curve:road.curve,offset:i/androidN,speed:2.2/road.curve.getLength(),lane:road.width/2+3});}
 for(let i=0;i<droneN;i++){const points=SPIRES.filter((_,j)=>j%2===i%2).map(([x,z],j)=>new T.Vector3(x,52+(i%3)*7,z));const curve=new T.CatmullRomCurve3(points,true);const object=drone(i%4===0);object.scale.setScalar(1.5);root.add(object);agents.push({object,curve,offset:i/droneN,speed:14/curve.getLength(),lane:0});}
 return {root,counts:{shuttles:30,freight:8,androids:24,drones:16},update(t){for(const a of agents){try{if(!a.curve||!a.object)continue;const span=a.curve.closed?1:2;let phase=(a.offset+t*a.speed)%span;if(!Number.isFinite(phase))continue;if(phase<0)phase+=span;const reverse=phase>1;const u=Math.min(.999,Math.max(.001,reverse?2-phase:phase));const p=a.curve.getPoint(u);const d=a.curve.getTangent(u);if(!p||!d||!Number.isFinite(p.x)||!Number.isFinite(d.x))continue;if(reverse)d.negate();a.object.position.copy(p);a.object.position.x-=d.z*a.lane;a.object.position.z+=d.x*a.lane;a.object.rotation.y=Math.atan2(d.x,d.z);if(a.limbs)a.limbs.forEach((l,j)=>l.rotation.x=Math.sin(t*4+j%2*Math.PI)*(j<2?.4:.55));}catch{}}}};}
