import {FACILITIES,LAKES,SPIRES,SITE,floorLayout} from './data.js';
const NS='http://www.w3.org/2000/svg';
function svgElement(tag,attrs={},text){const el=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs))el.setAttribute(key,String(value));if(text)el.textContent=text;return el;}
export function createCampusMap(container,onSelect){
 const panel=document.createElement('section');panel.id='map-fallback';panel.setAttribute('aria-label','Schematic campus map');
 const intro=document.createElement('div');intro.className='map-intro';const heading=document.createElement('h1');heading.textContent='Explore the campus plans.';const p=document.createElement('p');p.textContent='3D graphics are unavailable in this browser. Select a facility to explore its schematic floor plans.';intro.append(heading,p);panel.append(intro);
 const map=svgElement('svg',{viewBox:`${-SITE.width/2-20} ${-SITE.depth/2-20} ${SITE.width+40} ${SITE.depth+40}`,role:'group','aria-label':'35 facilities and their relative landscape positions'});
 map.append(svgElement('rect',{x:-SITE.width/2,y:-SITE.depth/2,width:SITE.width,height:SITE.depth,rx:90,fill:'#10292c',stroke:'#45746a','stroke-width':2}));
 for(const [x,z,rx,rz] of LAKES)map.append(svgElement('ellipse',{cx:x,cy:z,rx,ry:rz,fill:'#174b65',stroke:'#6b97a3','stroke-width':1}));
 for(let i=1;i<SPIRES.length;i++)map.append(svgElement('line',{x1:SPIRES[i-1][0],y1:SPIRES[i-1][1],x2:SPIRES[i][0],y2:SPIRES[i][1],stroke:'#9675c7','stroke-width':1.5,'stroke-dasharray':'4 7'}));
 for(const [x,z] of SPIRES)map.append(svgElement('circle',{cx:x,cy:z,r:4,fill:'#d3adff'}));
 for(const f of FACILITIES){const g=svgElement('g',{role:'button',tabindex:0,'aria-label':`${f.key} ${f.name}`,class:'map-facility'});g.append(svgElement('rect',{x:f.x-f.w/2,y:f.z-f.d/2,width:f.w,height:f.d,rx:3}));g.append(svgElement('text',{x:f.x,y:f.z+4,'text-anchor':'middle'},String(f.id).padStart(2,'0')));g.addEventListener('click',()=>onSelect(f.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(f.id);}});map.append(g);}
 panel.append(map);const note=document.createElement('small');note.textContent='Schematic overview · exterior locations follow the artwork · north at top';panel.append(note);container.replaceChildren(panel);
}
export function createPlanViewer(){
 const dialog=document.createElement('dialog');dialog.id='plan-dialog';dialog.setAttribute('aria-labelledby','plan-title');
 dialog.innerHTML='<div class="plan-heading"><div><span class="eyebrow" id="plan-id"></span><h2 id="plan-title"></h2></div><button id="plan-close" aria-label="Close floor plan">×</button></div><div class="plan-controls"><label>Floor <select id="plan-floor" aria-label="Plan floor"></select></label><p id="plan-dimensions"></p></div><div class="plan-body"><div id="floor-drawing"></div><div class="plan-room-panel"><span class="eyebrow">ROOM PROGRAM</span><div id="plan-rooms"></div><p id="plan-room-info" role="status"></p></div></div><p class="plan-note">Program-led fit-out within the supplied footprint. Partitions and heights are inferred, not surveyed interiors. Furniture is omitted from this plan.</p>';
 document.body.append(dialog);const query=s=>dialog.querySelector(s);let facility=null,lastFocus=null;
 function draw(level){const layout=floorLayout(facility,level),pad=1.6;query('#plan-dimensions').textContent=`${facility.width.toFixed(1)} × ${facility.depth.toFixed(1)} ft · 12 ft branching circulation`;const svg=svgElement('svg',{viewBox:`${-layout.w/2-pad} ${-layout.d/2-pad} ${layout.w+pad*2} ${layout.d+pad*2}`,role:'group','aria-label':`${facility.name}, ${facility.id===3?'basement':'floor'} ${level+1}, six proposed program zones`});
 svg.append(svgElement('rect',{x:-layout.w/2,y:-layout.d/2,width:layout.w,height:layout.d,fill:'#d9d4c6',stroke:'#68797c','stroke-width':.12}));
 for(const c of layout.circulation)svg.append(svgElement('rect',{x:c.x-c.w/2,y:c.z-c.d/2,width:c.w,height:c.d,fill:'#f4f0e4'}));
 for(const side of [-1,1]){const x=side<0?-layout.w/2:layout.w/2-layout.core;svg.append(svgElement('rect',{x,y:-layout.d/2,width:layout.core,height:layout.d,fill:'#69808a'}));svg.append(svgElement('text',{x:x+layout.core/2,y:0,'font-size':.6,'text-anchor':'middle',fill:'#fff',transform:`rotate(-90 ${x+layout.core/2} 0)`},'STAIR / LIFT / MEP'));}
 const buttons=[],rects=[];query('#plan-rooms').replaceChildren();
 const choose=i=>{buttons.forEach((b,j)=>b.setAttribute('aria-pressed',String(j===i)));rects.forEach((r,j)=>r.setAttribute('fill',j===i?'#d4a843':'#b4c5c6'));const r=layout.rooms[i];query('#plan-room-info').textContent=`${r.name} · ${(r.w/.3048).toFixed(1)} × ${(r.d/.3048).toFixed(1)} ft · ${(r.w*r.d/.09290304).toLocaleString(undefined,{maximumFractionDigits:0})} sq ft gross zone · ${r.height.toFixed(1)} m clear height`;};
 layout.rooms.forEach((r,i)=>{const g=svgElement('g',{role:'button',tabindex:0,'aria-label':`Room ${i+1}: ${r.name}`}),rect=svgElement('rect',{x:r.x-r.w/2+.08,y:r.z-r.d/2+.08,width:r.w-.16,height:r.d-.16,fill:'#b4c5c6',stroke:'#394f56','stroke-width':.12});rects.push(rect);g.append(rect);g.append(svgElement('text',{x:r.x,y:r.z+.3,'font-size':1.1,'text-anchor':'middle',fill:'#10232c'},String(i+1).padStart(2,'0')));const dx=Math.cos(r.angle)*r.doorWidth/2,dz=-Math.sin(r.angle)*r.doorWidth/2;g.append(svgElement('line',{x1:r.doorX-dx,y1:r.doorZ-dz,x2:r.doorX+dx,y2:r.doorZ+dz,stroke:'#f4f0e4','stroke-width':.28}));g.addEventListener('click',()=>choose(i));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(i);}});svg.append(g);const b=document.createElement('button');b.textContent=`${i+1}. ${r.name}`;b.onclick=()=>choose(i);buttons.push(b);query('#plan-rooms').append(b);});
 query('#floor-drawing').replaceChildren(svg);choose(0);
 }
 query('#plan-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>lastFocus?.focus());query('#plan-floor').onchange=e=>draw(Number(e.target.value));
 return {open(f){facility=f;lastFocus=document.activeElement;query('#plan-id').textContent=`${f.key} · SCHEMATIC FLOOR PLAN`;query('#plan-title').textContent=f.name;query('#plan-floor').replaceChildren();for(let i=0;i<f.levels;i++){const o=document.createElement('option');o.value=i;o.textContent=f.id===3?`B${i+1}`:`L${String(i+1).padStart(2,'0')}`;query('#plan-floor').append(o);}draw(0);dialog.showModal();},close(){dialog.close();}};
}
