import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {animate} from 'animejs';
import {FACILITIES,DISTRICTS,SPIRES} from './campus/data.js';
import {createFacility} from './campus/buildings.js';
import {createLandscape,createInfrastructure} from './campus/landscape.js';
import {createFleets} from './campus/fleets.js';
import {materials} from './campus/geometry.js';
const $=s=>document.querySelector(s);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let renderer,scene,camera,controls,composer,landscape,infrastructure,fleets,interior=null,selected=null,flight=null,flyover=false,showLabels=true,entering=false,clock=0;
const buildings=[],markers=[];const mobile=matchMedia('(max-width:760px)').matches;let sun,hemi,rim;
function message(text){$('#status').textContent=text;}
function sheet(){document.body.classList.toggle('sheet-open',!$('#detail').hidden||!$('#directory').hidden);}
function closeDirectory(){$('#directory').hidden=true;$('#directory-toggle').setAttribute('aria-expanded','false');sheet();}
function updateDirectory(){const q=$('#search').value.toLowerCase().trim(),district=Number($('#district').value);const fs=FACILITIES.filter(f=>(!district||f.district===district)&&(!q||`${f.key} ${f.id} ${f.name}`.toLowerCase().includes(q)));$('#facility-list').replaceChildren();for(const f of fs){const button=document.createElement('button');button.innerHTML=`<span>${String(f.id).padStart(2,'0')}</span>${f.name}`;button.onclick=()=>select(f.id);$('#facility-list').append(button);}if(!fs.length){const p=document.createElement('p');p.textContent='No matching facilities.';$('#facility-list').append(p);}}
function select(id){selected=FACILITIES.find(f=>f.id===id);if(!selected)return;const f=selected;$('#detail').hidden=false;if(innerWidth<761)closeDirectory();sheet();$('#facility-key').textContent=f.key;$('#facility-name').textContent=f.name;$('#facility-district').textContent=DISTRICTS[f.district];$('#facility-area').textContent=f.design_area.toLocaleString();$('#facility-floors').textContent=f.levels;$('#facility-program').textContent=f.program[0].split(';').slice(0,4).join(' · ');$('#area-note').textContent=f.assumedArea?'Area is a design-package assumption; original allowance remains unresolved.':'Program and floor count from the supplied schematic design package.';markers.forEach(({el,f})=>el.classList.toggle('selected',f.id===id));message(`${f.key} selected · exterior or interior tour available`);}
function moveCamera(position,target){flight?.pause();flyover=false;$('#tour').classList.remove('active');const state={x:camera.position.x,y:camera.position.y,z:camera.position.z,tx:controls.target.x,ty:controls.target.y,tz:controls.target.z};flight=animate(state,{x:position[0],y:position[1],z:position[2],tx:target[0],ty:target[1],tz:target[2],duration:reduced?0:1200,ease:'inOutCubic',onUpdate:()=>{camera.position.set(state.x,state.y,state.z);controls.target.set(state.tx,state.ty,state.tz);controls.update();},onComplete:()=>flight=null});}
function focus(){if(!selected)return;const f=selected;moveCamera([f.x+f.w*1.2,f.h+f.w*.8,f.z+f.d*1.9],[f.x,f.h*.35,f.z]);}
function setDay(day){$('#day').setAttribute('aria-pressed',String(day));hemi.intensity=day?2:1.45;sun.intensity=day?3:2.5;sun.color.set(day?0xfff1d5:0xffd3a2);scene.background.set(day?0x9dc0d0:0x4d697d);scene.fog.color.copy(scene.background);materials.warm.emissiveIntensity=day?.2:1.2;renderer.toneMappingExposure=day?1.1:1.15;}
async function enter(){if(!selected||entering||interior)return;entering=true;$('#enter').disabled=true;$('#enter').textContent='Opening interior…';const f=selected;try{const {createInterior}=await import('./campus/interior.js');flight?.pause();flyover=false;$('#interior').hidden=false;$('#inside-key').textContent=f.key;$('#inside-name').textContent=f.name;$('#floor-select').replaceChildren();for(let i=0;i<f.levels;i++){const option=document.createElement('option');option.value=i;option.textContent=f.id===3?`B${i+1}`:`L${String(i+1).padStart(2,'0')}`;$('#floor-select').append(option);}interior=createInterior($('#interior-canvas'),f,{reduced,onRoom:name=>$('#room-status').textContent=name,onFloor:(l,rooms)=>{$('#floor-select').value=l;$('#room-list').replaceChildren();rooms.forEach((r,i)=>{const button=document.createElement('button');button.textContent=`${i+1}. ${r.name}`;button.onclick=()=>interior?.visit(i);$('#room-list').append(button);});}});$('#interior-canvas').focus();message('');}catch(e){console.error(e);$('#interior').hidden=true;interior?.dispose();interior=null;message('Interior could not open. Please try again.');}finally{entering=false;$('#enter').disabled=false;$('#enter').innerHTML='Explore inside <span>↗</span>';}}
function exit(){interior?.dispose();interior=null;$('#interior').hidden=true;renderer?.setSize(innerWidth,innerHeight);$('#enter').focus();}
function bind(){DISTRICTS.forEach((name,i)=>{const option=document.createElement('option');option.value=i;option.textContent=name;$('#district').append(option);});updateDirectory();$('#search').oninput=updateDirectory;$('#district').onchange=updateDirectory;
 $('#directory-toggle').onclick=()=>{const open=$('#directory').hidden;$('#directory').hidden=!open;$('#directory-toggle').setAttribute('aria-expanded',String(open));if(open&&innerWidth<761)$('#detail').hidden=true;sheet();if(open)$('#search').focus();};$('#directory-close').onclick=closeDirectory;$('#detail-close').onclick=()=>{$('#detail').hidden=true;sheet();};$('#focus').onclick=focus;$('#enter').onclick=enter;$('#exit-interior').onclick=exit;$('#floor-select').onchange=e=>interior?.setFloor(Number(e.target.value));
 $('#aerial').onclick=()=>moveCamera([90,mobile?1150:950,mobile?1230:1050],[0,0,0]);$('#north').onclick=()=>moveCamera([-100,750,-1000],[0,0,0]);$('#ground').onclick=()=>{if(selected){const f=selected;moveCamera([f.x,5,f.z+f.d/2+35],[f.x,f.h*.4,f.z]);}else moveCamera([-280,8,285],[-130,25,110]);};$('#tour').onclick=()=>{flight?.pause();flyover=!flyover;$('#tour').classList.toggle('active',flyover);};$('#day').onclick=()=>setDay($('#day').getAttribute('aria-pressed')!=='true');$('#layers-toggle').onclick=()=>{$('#layers').hidden=!$('#layers').hidden;$('#layers-toggle').setAttribute('aria-expanded',String(!$('#layers').hidden));};$('#labels').onclick=()=>{showLabels=!showLabels;$('#labels').setAttribute('aria-pressed',String(showLabels));$('#markers').hidden=!showLabels;};$('#mesh-layer').onchange=e=>infrastructure.setNetwork(e.target.checked);$('#energy-layer').onchange=e=>infrastructure.setEnergy(e.target.checked);$('#fleet-layer').onchange=e=>fleets.root.visible=e.target.checked;
 document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);interior?.hold(b.dataset.move,true);};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>interior?.hold(b.dataset.move,false));});window.addEventListener('blur',()=>{document.querySelectorAll('[data-move]').forEach(b=>interior?.hold(b.dataset.move,false));});window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(interior)exit();else{closeDirectory();$('#detail').hidden=true;$('#layers').hidden=true;sheet();}}});
}
async function boot(){
 renderer=new T.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.25:1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=T.PCFSoftShadowMap;$('#app').append(renderer.domElement);
 scene=new T.Scene();scene.background=new T.Color(0x4d697d);scene.fog=new T.Fog(0x4d697d,1100,2700);camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.5,4000);camera.position.set(90,mobile?1150:950,mobile?1230:1050);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2-.015;controls.minDistance=8;controls.maxDistance=2300;controls.update();controls.addEventListener('start',()=>{flight?.pause();flight=null;flyover=false;$('#tour').classList.remove('active');});
 const pmrem=new T.PMREMGenerator(renderer);const env=new RoomEnvironment();scene.environment=pmrem.fromScene(env,.04).texture;env.dispose();pmrem.dispose();scene.environmentIntensity=.4;
 hemi=new T.HemisphereLight(0xc9deef,0x29372b,1.45);scene.add(hemi);sun=new T.DirectionalLight(0xffd3a2,2.5);sun.position.set(-500,750,-500);sun.castShadow=!mobile;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-650;sun.shadow.camera.right=650;sun.shadow.camera.top=650;sun.shadow.camera.bottom=-650;sun.shadow.camera.far=2000;sun.shadow.normalBias=.6;scene.add(sun);rim=new T.DirectionalLight(0x76aec7,.7);rim.position.set(350,200,400);scene.add(rim);
 landscape=createLandscape();scene.add(landscape.root);for(const f of FACILITIES){const group=createFacility(f);buildings.push(group);scene.add(group);const el=document.createElement('button');el.className='marker';el.textContent=String(f.id).padStart(2,'0');el.setAttribute('aria-label',`${f.key} ${f.name}`);el.onclick=()=>select(f.id);$('#markers').append(el);markers.push({el,f});}
 infrastructure=createInfrastructure();scene.add(infrastructure.root);fleets=createFleets(landscape.roads);scene.add(fleets.root);
 new GLTFLoader().load(`${import.meta.env.BASE_URL}models/synergy-node.glb`,g=>{for(const [x,z] of SPIRES){const node=g.scene.clone(true);node.position.set(x+13,0,z);node.name='Blender physical synergy node';scene.add(node);}},undefined,e=>{console.warn('Synergy node detail unavailable',e);message('Some node detail failed to load; mesh towers remain available.');});
 if(!mobile){composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.2,.35,1.05));composer.addPass(new OutputPass());}
 const ray=new T.Raycaster(),pointer=new T.Vector2();let start=null;renderer.domElement.addEventListener('pointerdown',e=>{start=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>7)return;pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(buildings,true)[0];if(hit)select(hit.object.userData.facility);start=null;});
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();message('3D graphics paused. Reload the page to restore the campus.');});
 bind();setDay(false);let last=performance.now(),frames=0;const projected=new T.Vector3();
 function render(now){requestAnimationFrame(render);const dt=Math.min((now-last)/1000,.05);last=now;if(interior||document.hidden)return;if(!reduced)clock+=dt;landscape.update(clock);infrastructure.update(clock);fleets.update(clock);if(flyover&&!reduced){camera.position.set(Math.sin(clock*.035)*1120,720,Math.cos(clock*.035)*1120);controls.target.set(0,0,0);}controls.update();if(composer)composer.render();else renderer.render(scene,camera);
 if(++frames%3===0&&showLabels){const far=camera.position.length()>800;const occupied=[];for(const {el,f} of markers){projected.set(f.x,f.h+8,f.z).project(camera);const x=(projected.x*.5+.5)*innerWidth,y=(-projected.y*.5+.5)*innerHeight;let visible=projected.z<1&&projected.z>-1&&x>10&&x<innerWidth-10&&y>90&&y<innerHeight-135;if(mobile&&far&&f.id%2===0)visible=false;if(visible&&occupied.some(p=>Math.hypot(p[0]-x,p[1]-y)<28))visible=false;if(visible)occupied.push([x,y]);el.hidden=!visible;el.style.left=x+'px';el.style.top=y+'px';}}
 }
 window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer?.setSize(innerWidth,innerHeight);});
 render(performance.now());$('#loading').hidden=true;
}
boot().catch(e=>{console.error(e);$('#load-message').textContent='The 3D campus could not start. Try a WebGL-enabled browser or reload.';const retry=document.createElement('button');retry.textContent='Reload campus';retry.onclick=()=>location.reload();$('#loading').append(retry);});
